### ISSUE TITLE
ERROR  <class 'cv2.VideoWriter'> returned a result with an error set

### ISSUE THREAD

**Issue by DIpakbhagat26** [ghostbbbmt/Traffic-Sign-Classification#2]
HI when i am trying to run the program i am getting an error \

```
cv2.error: C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp:389: error: (-215) result || fps != 0 in function cvCreateVideoWriterWithPreference


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Downloads\Traffic-Sign-Classification-master (1)\Traffic-Sign-Classification-master\main.py", line 384, in <module>
    main(args)
  File "G:\Downloads\Traffic-Sign-Classification-master (1)\Traffic-Sign-Classification-master\main.py", line 241, in main
    out = cv2.VideoWriter('output.avi',fourcc, fps , (640,480))
SystemError: <class 'cv2.VideoWriter'> returned a result with an error set

```
please help

**Comment by hoanglehaithanh** [comment]
Maybe this link can help you. and please check your input video

https://github.com/ContinuumIO/anaconda-issues/issues/223
